apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-sf
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-sf
  template:
    metadata:
      labels:
        app: nginx-sf
    spec:
      containers:
        - name: nginx
          image: nginx:1.21.1-alpine
